# Generated by Django 4.2.10 on 2024-02-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fb_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fb_url',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='fb_id',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='fb_url',
        ),
        migrations.AddField(
            model_name='event',
            name='source_url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Source URL'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='source_url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Source URL'),
        ),
    ]
