# Generated by Django 4.2.10 on 2024-06-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_fb_id_remove_event_fb_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
