# Generated by Django 4.2.10 on 2024-06-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.film'),
        ),
    ]
