# Generated by Django 4.2.10 on 2024-06-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhost',
            name='facebook_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='facebook_id',
            field=models.URLField(blank=True, null=True),
        ),
    ]
