# Generated by Django 4.2.10 on 2024-06-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_download_size_historicalhost_facebook_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhost',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
