# Generated by Django 4.2.10 on 2024-06-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_historicalhost_facebook_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='scroll_amount',
            new_name='scroll_count',
        ),
    ]
