# Generated by Django 4.2.10 on 2024-06-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_scroll_amount_download_scroll_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fully_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='fully_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
