# Generated by Django 4.2.10 on 2024-06-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_fully_scraped_historicalevent_fully_scraped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhost',
            name='past_event_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='historicalhost',
            name='profile_picture',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='past_event_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
