# Generated by Django 4.2.10 on 2024-06-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_historicalhost_past_event_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_str',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='location_str',
        ),
        migrations.AlterField(
            model_name='film',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='film_banners/'),
        ),
    ]
