# Generated by Django 4.2.10 on 2024-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_location_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
