# Generated by Django 4.2.10 on 2024-07-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_filmgenre_rename_banner_film_backdrop_film_is_adult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.tag'),
        ),
        migrations.AddField(
            model_name='host',
            name='auto_add_tags',
            field=models.ManyToManyField(blank=True, related_name='auto_adder_hosts', to='events.tag'),
        ),
    ]
