# Generated by Django 5.0.7 on 2024-07-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_tag_event_tags_host_auto_add_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.TextField()),
                ('domain', models.CharField(default='.facebook.com', max_length=256)),
                ('path', models.CharField(default='/', max_length=256)),
                ('cookie_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.cookieset')),
            ],
        ),
    ]
