# Generated by Django 4.2.13 on 2024-07-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_cookie_cookie_set_alter_cookie_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cinema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='cinema',
            field=models.BooleanField(default=False),
        ),
    ]
