# Generated by Django 4.2.13 on 2024-07-15 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_cinema_historicalevent_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256)),
                ('boundary', models.BooleanField(default=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='events.tag')),
            ],
        ),
    ]
